# Generated by Django 4.2.20 on 2025-04-19 10:59

from django.db import migrations, models
import django.utils.timezone

def set_initial_school_year(apps, schema_editor):
    ElectionSettings = apps.get_model('admin_panel', 'ElectionSettings')
    current_year = django.utils.timezone.now().year
    for settings in ElectionSettings.objects.all():
        settings.school_year = f"{current_year}-{current_year + 1}"
        settings.is_active = True
        settings.save()

class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionsettings',
            name='school_year',
            field=models.CharField(default='2024-2025', help_text='Format: YYYY-YYYY', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electionsettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_initial_school_year),
    ]
