# Generated by Django 4.2.20 on 2025-04-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_committeeaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminactivity',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Admin Activities'},
        ),
        migrations.RenameField(
            model_name='adminactivity',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='adminactivity',
            old_name='description',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='adminactivity',
            name='action_model',
        ),
        migrations.AddField(
            model_name='adminactivity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminactivity',
            name='action',
            field=models.CharField(max_length=255),
        ),
    ]
