# Generated by Django 4.2.20 on 2025-04-05 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_migrate_user_to_user_profile'),
    ]

    operations = [
        # First, make user_profile required in Candidate model
        migrations.AlterField(
            model_name='candidate',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile'),
        ),
        
        # Make user_profile required in Vote model
        migrations.AlterField(
            model_name='vote',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile'),
        ),
        
        # Remove user field from Candidate
        migrations.RemoveField(
            model_name='candidate',
            name='user',
        ),
        
        # Remove user field from Vote
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        
        # Update the unique constraint for Vote
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user_profile', 'candidate'), name='unique_user_profile_vote'),
        ),
        
        # Remove the conditional constraint now that user_profile is no longer nullable
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_vote_user_profile_candidate',
        ),
        
        # Update the unique constraint for Candidate
        migrations.RemoveConstraint(
            model_name='candidate',
            name='unique_candidate_user_profile',
        ),
        
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('user_profile',), name='unique_candidate_user_profile'),
        ),
    ]
