# Generated by Django 4.2.18 on 2025-03-23 04:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('PRESIDENT', 'President'), ('VICE_PRESIDENT', 'Vice President'), ('SECRETARY', 'Secretary'), ('TREASURER', 'Treasurer'), ('AUDITOR', 'Auditor'), ('PIO', 'Public Information Officer'), ('REPRESENTATIVE', 'Representative'), ('GOVERNOR', 'Governor'), ('VICE_GOVERNOR', 'Vice Governor'), ('SEC_GOVERNOR', 'Secretary'), ('TRES_GOVERNOR', 'Treasurer'), ('AUD_GOVERNOR', 'Auditor'), ('PIO_GOVERNOR', 'Public Information Officer'), ('MAYOR', 'Mayor'), ('VICE_MAYOR', 'Vice Mayor'), ('SEC_LOCAL', 'Secretary'), ('TRES_LOCAL', 'Treasurer'), ('AUD_LOCAL', 'Auditor'), ('PIO_LOCAL', 'Public Information Officer'), ('REP_LOCAL', 'Representative')], max_length=50)),
                ('college', models.CharField(choices=[('CAS', 'College of Arts and Sciences'), ('CAF', 'College of Agriculture and Forestry'), ('CCJE', 'College of Criminal Justice Education'), ('CBA', 'College of Business Administration'), ('CTED', 'College of Teacher Education'), ('CIT', 'College of Industrial Technology')], max_length=100)),
                ('platform', models.TextField()),
                ('achievements', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(max_length=100)),
                ('year_level', models.CharField(max_length=20)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VotingPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('ONGOING', 'Ongoing'), ('ENDED', 'Ended')], default='NOT_STARTED', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('college', models.CharField(choices=[('CAS', 'College of Arts and Sciences'), ('CAF', 'College of Agriculture and Forestry'), ('CCJE', 'College of Criminal Justice Education'), ('CBA', 'College of Business Administration'), ('CTED', 'College of Teacher Education'), ('CIT', 'College of Industrial Technology')], max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('year_level', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Fifth Year')], max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(99)])),
                ('contact_number', models.CharField(max_length=15)),
                ('face_data', models.BinaryField(blank=True, editable=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.candidate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'candidate')},
            },
        ),
    ]
