# Generated by Django 4.2.20 on 2025-05-05 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFacePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='face_data/')),
                ('embedding', models.TextField(blank=True, null=True)),
                ('angle', models.CharField(help_text='Angle/position of the face in the photo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_photos', to='user.userprofile')),
            ],
            options={
                'verbose_name': 'User Face Photo',
                'verbose_name_plural': 'User Face Photos',
                'db_table': 'user_face_photo',
            },
        ),
    ]
