# Generated by Django 4.2.20 on 2025-05-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userfacephoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfacephoto',
            options={},
        ),
        migrations.RemoveField(
            model_name='userfacephoto',
            name='angle',
        ),
        migrations.RemoveField(
            model_name='userfacephoto',
            name='embedding',
        ),
        migrations.AlterModelTable(
            name='userfacephoto',
            table=None,
        ),
        migrations.DeleteModel(
            name='FaceData',
        ),
    ]
