# Generated by Django 4.2.20 on 2025-04-01 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_facedata_candidateprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['position', 'college', 'department', 'year_level']},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='department',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='gender',
            new_name='sex',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='face_data',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Auditor', 'Auditor'), ('Public Information Officer', 'Public Information Officer'), ('Representative', 'Representative'), ('Governor', 'Governor'), ('Vice Governor', 'Vice Governor'), ('Secretary (College)', 'Secretary (College)'), ('Treasurer (College)', 'Treasurer (College)'), ('Auditor (College)', 'Auditor (College)'), ('Public Information Officer (College)', 'Public Information Officer (College)'), ('Department Representative', 'Department Representative')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='year_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('position', 'college', 'department', 'year_level')},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='platform',
        ),
    ]
