# Generated by Django 4.2.20 on 2025-05-05 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userfacephoto_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFacePhoto',
            new_name='Photo',
        ),
    ]
