# Generated by Django 4.2.20 on 2025-04-19 16:39

from django.db import migrations, models

def set_default_school_year(apps, schema_editor):
    Vote = apps.get_model('user', 'Vote')
    # Get the current active school year from ElectionSettings
    ElectionSettings = apps.get_model('admin_panel', 'ElectionSettings')
    try:
        current_settings = ElectionSettings.objects.filter(is_active=True).first()
        default_year = current_settings.school_year if current_settings else '2024-2025'
    except:
        default_year = '2024-2025'
    
    # Update all existing votes with the default school year
    Vote.objects.filter(school_year__isnull=True).update(school_year=default_year)

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_add_user_profile_school_year'),
        ('admin_panel', '0002_auto_20250419_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='school_year',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.RunPython(set_default_school_year),
        migrations.AlterField(
            model_name='vote',
            name='school_year',
            field=models.CharField(max_length=9, default='2024-2025'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user_profile', 'candidate', 'school_year')},
        ),
    ]
