# Generated by Django 4.2.20 on 2025-05-09 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_rename_userfacephoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
