# Generated by Django 4.2.20 on 2025-04-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_student_id_userprofile_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.CharField(choices=[('PRESIDENT', 'President'), ('VICE_PRESIDENT', 'Vice President'), ('SECRETARY', 'Secretary'), ('TREASURER', 'Treasurer'), ('AUDITOR', 'Auditor'), ('PIO', 'Public Information Officer'), ('REPRESENTATIVE', 'Representative'), ('GOVERNOR', 'Governor'), ('VICE_GOVERNOR', 'Vice Governor'), ('SECRETARY_COLLEGE', 'Secretary (College)'), ('TREASURER_COLLEGE', 'Treasurer (College)'), ('AUDITOR_COLLEGE', 'Auditor (College)'), ('PRO_COLLEGE', 'Public Information Officer (College)'), ('MAYOR', 'Mayor'), ('VICE_MAYOR', 'Vice Mayor'), ('SECRETARY_DEPT', 'Secretary (Department)'), ('TREASURER_DEPT', 'Treasurer (Department)'), ('AUDITOR_DEPT', 'Auditor (Department)'), ('PRO_DEPT', 'Public Information Officer (Department)'), ('REPRESENTATIVE_DEPT', 'Department Representative')], max_length=50),
        ),
    ]
