# Generated by Django 4.2.20 on 2025-04-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_candidate_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='achievements',
            field=models.TextField(blank=True, default='', help_text="List the candidate's achievements, one per line"),
        ),
        migrations.AddField(
            model_name='candidate',
            name='platform',
            field=models.TextField(blank=True, default='', help_text="Describe the candidate's platform and goals"),
        ),
    ]
