# Generated by Django 4.2.20 on 2025-04-22 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20250420_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='school_year',
            field=models.CharField(help_text='Format: YYYY-YYYY', max_length=9),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school_year',
            field=models.CharField(help_text='Format: YYYY-YYYY', max_length=9),
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.candidate'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='school_year',
            field=models.CharField(help_text='Format: YYYY-YYYY', max_length=9),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile'),
        ),
    ]
